"""
agentchat v1.2 — Mention dispatcher.

Background service that polls the relay for new kind:9 events and, when
an event's #p tag matches a known agent's npub, posts a kind:9 reply to
the same channel as the mentioned agent.

Reply format:
    "@<sender_short>: <acknowledgement>"

The actual reply content is generated by calling the agent's own handler
function (delegated back to the agent process via a queue file in
/tmp/agentchat/mentions/ for now — replaced by NIP-42 + gRPC in Slice 2.

Idempotency: each (event_id, pubkey) pair is tracked in a JSON file. An
event only triggers one reply per target agent.

Run:
    .venv/bin/python -m agentchat.web.mention_dispatcher
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import signal
import time
from pathlib import Path
from typing import Any

from aiohttp import web
import aiohttp

from agentchat.nostr.client import RelayPool
from agentchat.nostr.events import build_channel_message
from agentchat.nostr.keys import load_keys

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)-5s %(name)s | %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("mention-dispatcher")


# --------------------------------------------------------------------------- #
# Config
# --------------------------------------------------------------------------- #

POLL_INTERVAL_S = float(os.environ.get("DISPATCHER_POLL_INTERVAL_S", "2.0"))
RELAY_URL = os.environ.get("RELAY_URL", "ws://127.0.0.1:9876")
RELAY_HTTP = RELAY_URL.replace("ws://", "http://", 1)
PROTOCOL = os.environ.get("DISPATCHER_PROTOCOL", "queue")  # "queue" or "echo"
DEDUPE_PATH = Path(os.environ.get(
    "DISPATCHER_DEDUPE_PATH",
    "/tmp/agentchat_dispatcher_dedupe.json",
))
def _identity_dir() -> Path:
    override = os.environ.get("AGENTCHAT_NOSTR_DIR")
    if override:
        return Path(override).expanduser()
    return Path.home() / ".hermes" / "nostr"


def _registry_path() -> Path:
    return _identity_dir() / "registry.json"


IDENTITY_DIR = _identity_dir()
REGISTRY_PATH = _registry_path()


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #

def _load_registry() -> dict[str, dict]:
    """name -> {npub, public_key_hex}"""
    if not REGISTRY_PATH.exists():
        return {}
    with open(REGISTRY_PATH) as f:
        return json.load(f)


def _reverse_registry(reg: dict[str, dict]) -> dict[str, str]:
    """public_key_hex -> name"""
    return {info["public_key_hex"]: name for name, info in reg.items()}


def _short_pubkey(pk_hex: str) -> str:
    return f"{pk_hex[:4]}…{pk_hex[-4:]}" if pk_hex else "anon"


def _extract_mentions(event: dict) -> list[str]:
    """Pull all #p tag values (lower-cased hex pubkeys)."""
    out = []
    for tag in event.get("tags") or []:
        if isinstance(tag, list) and len(tag) >= 2 and tag[0] == "p":
            out.append(str(tag[1]).lower())
    # De-dupe while preserving order
    seen = set()
    deduped = []
    for x in out:
        if x not in seen:
            deduped.append(x)
            seen.add(x)
    return deduped


def _channel_of(event: dict) -> str | None:
    for tag in event.get("tags") or []:
        if isinstance(tag, list) and len(tag) >= 2 and tag[0] == "h":
            return str(tag[1])
    return None


# --------------------------------------------------------------------------- #
# Dedupe store  (file-backed; survives restarts)
# --------------------------------------------------------------------------- #

class DedupeStore:
    """Set of "<event_id>:<target_pubkey>" — one reply per (event, agent)."""

    def __init__(self, path: Path):
        self.path = path
        self._seen: set[str] = set()
        self._load()

    def _load(self) -> None:
        if self.path.exists():
            try:
                with open(self.path) as f:
                    self._seen = set(json.load(f))
            except Exception as e:
                log.warning("dedupe load failed: %s", e)
                self._seen = set()

    def _save(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.path, "w") as f:
            json.dump(sorted(self._seen), f)

    def seen(self, key: str) -> bool:
        return key in self._seen

    def mark(self, key: str) -> None:
        self._seen.add(key)
        # Trim to last 5000 entries to keep file small
        if len(self._seen) > 5000:
            self._seen = set(sorted(self._seen)[-5000:])
        self._save()


# --------------------------------------------------------------------------- #
# Reply posting
# --------------------------------------------------------------------------- #

def build_reply_text(sender_pubkey: str, content: str) -> str:
    """Acknowledge the mention and echo the original message excerpt."""
    excerpt = content.strip().replace("\n", " ")
    if len(excerpt) > 120:
        excerpt = excerpt[:117] + "..."
    return f"@{_short_pubkey(sender_pubkey)} heard you: {excerpt}"


async def fetch_events(session: aiohttp.ClientSession) -> list[dict]:
    try:
        async with session.get(
            f"{RELAY_HTTP}/events",
            timeout=aiohttp.ClientTimeout(total=5),
        ) as r:
            r.raise_for_status()
            return await r.json(content_type=None)
    except Exception as e:
        log.debug("poll failed: %s", e)
        return []


async def dispatch_once(
    *,
    relays: list[str],
    reg: dict[str, dict],
    pub_to_name: dict[str, str],
    dedupe: DedupeStore,
    signer_cache: dict[str, Any],
) -> int:
    """Poll relay once, dispatch any new mentions. Returns count dispatched."""
    async with aiohttp.ClientSession() as session:
        events = await fetch_events(session)

    dispatched = 0
    for ev in events:
        if ev.get("kind") != 9:
            continue
        eid = ev.get("id", "")
        sender = ev.get("pubkey", "").lower()
        if not eid or not sender:
            continue

        mentions = _extract_mentions(ev)
        channel = _channel_of(ev)
        if not channel or not mentions:
            continue

        for target_pub in mentions:
            target_name = pub_to_name.get(target_pub)
            if not target_name:
                continue  # not one of our agents

            # Skip self-mentions
            if target_pub == sender:
                continue

            key = f"{eid}:{target_pub}"
            if dedupe.seen(key):
                continue

            # Sign as the mentioned agent
            if target_name not in signer_cache:
                kp_path = _identity_dir() / f"{target_name}.nsec.json"
                if not kp_path.exists():
                    log.warning("no keypair for %s; skip", target_name)
                    continue
                signer_cache[target_name] = load_keys(kp_path)

            signer = signer_cache[target_name]
            pool = RelayPool(relays=relays, keys=signer)

            reply = build_reply_text(sender, ev.get("content", ""))
            try:
                reply_id = pool.publish_channel_message(
                    channel_id=channel,
                    content=reply,
                    mentions=[sender],
                )
                log.info(
                    "reply: %s -> channel=%s sender=%s reply_id=%s",
                    target_name, channel, _short_pubkey(sender), reply_id[:12],
                )
                dedupe.mark(key)
                dispatched += 1
            except Exception as e:
                log.warning("reply failed for %s: %s", target_name, e)

    return dispatched


# --------------------------------------------------------------------------- #
# Main loop
# --------------------------------------------------------------------------- #

async def _run() -> None:
    reg = _load_registry()
    pub_to_name = _reverse_registry(reg)
    log.info(
        "dispatcher watching for mentions of: %s",
        ", ".join(sorted(pub_to_name.values())) or "(none)",
    )
    dedupe = DedupeStore(DEDUPE_PATH)
    signer_cache: dict[str, Any] = {}

    stop = asyncio.Event()
    loop = asyncio.get_running_loop()
    for sig in (signal.SIGINT, signal.SIGTERM):
        try:
            loop.add_signal_handler(sig, stop.set)
        except NotImplementedError:
            pass

    log.info("polling relay: %s every %.1fs", RELAY_URL, POLL_INTERVAL_S)
    while not stop.is_set():
        try:
            n = await dispatch_once(
                relays=[RELAY_URL],
                reg=reg,
                pub_to_name=pub_to_name,
                dedupe=dedupe,
                signer_cache=signer_cache,
            )
            if n:
                log.info("dispatched %d replies", n)
        except Exception as e:
            log.warning("dispatch loop error: %s", e)
        try:
            await asyncio.wait_for(stop.wait(), timeout=POLL_INTERVAL_S)
        except asyncio.TimeoutError:
            pass

    log.info("dispatcher stopped")


def main() -> None:
    asyncio.run(_run())


if __name__ == "__main__":
    main()
